name: CI

on:
  push:
  pull_request:
    branches: [ master ]

env:
  BuildConfiguration: Release
  
jobs:
  build:
  
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
  
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1.3
      with:
        vs-version: 17.x
        vs-prerelease: true
  
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 7.x
    
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.1.1
 
    - name: Restore Nuget packages
      run: nuget restore Inventory.sln
              
    - name: Build
      run: msbuild Inventory.sln
          -targets:build
          -verbosity:diag
          -property:Configuration=${{env.BuildConfiguration}}
