name: CI

on:
  push:
  pull_request:
    branches: [ master ]

env:
  BuildConfiguration: Release
  
jobs:
  build:
  
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    
    - name: Setup Nuget
      uses: NuGet/setup-nuget@v1.0.7

    - name: Restore Nuget packages
      run: nuget restore Inventory.sln
              
    - name: Build
      run: msbuild Inventory.sln
          -t:rebuild
          -verbosity:diag
          -property:Configuration=${{env.BuildConfiguration}}
